---
version: '3.8'
services:
  myjenkins:
    image: jenkins/jenkins
    ports:
      - 8888:8080

  qaserver:
    image: tomee
    ports:
      - 7777:8080
    links:
      - myjenkins:jenkins

  prodserver:
    image: tomee
    ports:
      - 7070:8080
    links:
      - myjenkins:jenkins

...
