---
version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: vinod
    container_name: mydb

  apache:
    image: httpd
    ports:
      - 8080:80
    links:
      - mydb:mysql
    container_name: apache

  php:
    image: php:7.2-apache
    links:
      - mydb:mysql
      - apache:httpd
    container_name: myphp

...
